CREATEACCOUNT = 'Register'
USERLOGIN = 'Login'
USERLOGOUT = 'Logout'
MODIFYACCOUNT = 'Profile'
DELETEACCOUNT = 'Delete'
SEARCHACCOUNT = 'Search'

FRIENDREQUEST = 'Invite'
FRIENDREQUESTSHOW = 'ShowInvite'
CHANGESTATE = 'updateState'
ASKINGINFO = 'AskingUpdate'
SHOWFRIENDREQUEST = 'ShowRequest'
ACCEPTINVITE = 'AcceptInvite'
REJECTINVITE = 'RejectInvite'

GETPROFILE = 'getProfile'
CHATTOONE = 'ChatToOne'
GETFRIENDPROFILE = 'getFriendProfile'
SOUNDREQUEST = 'RequestForMic'
SENDSOUND = 'SendVoice'

CREATEGROUP = 'CreateGroup'
ADDMEMBER = 'AddMember'
REMOVEMEMBER = 'LeaveGroup'
CHATTOGROUP = 'ChatToGroup'

REQUESTIP = 'RequestIP'

PIKAREQUEST = 'RequestPika'
ACCEPTPIKA = 'PikaAccept'
REJECTPIKA = 'PikaReject'
